name: nox tests

on: [pull_request, workflow_dispatch]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      
      - name: Setup Nox
        uses: wntrblm/nox@2024.10.09
        with:
          python-versions: "3.11, 3.12"
      
      - name: Run tests
        run: nox